# Header
menu:
  Home: /
  About: /about
  Archives: /archives
  Tag: /tags
  Github: https://github.com/leiadot
  Facebook: https://www.facebook.com/CodingGirlHy2
rss: /atom.xml

# Content
excerpt_link: 閱讀全文
fancybox: true

# Miscellaneous
google_analytics: UA-87257429-1
favicon: /favicon.ico

# open graph
twitter:
image: /logo.png
google_plus:
fb_admins:
fb_app_id: 